---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# Image will be published to ghcr.io/<user>/<name>
name: desktop-os
description: This is my personal OS image.

# Base image and version
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41  # Use "latest" if you want bleeding edge updates

# Module configuration
modules:
  - type: files
    files:
      - source: system
        destination: /  # Copies contents of system/* to the root of the image

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com
    install:
      - brave-browser
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - scope: system
        repo:
          title: Flathub (system)

  - type: signing  # Enables image signing and verification support
